version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: NJsonSchema
    versions:
    - 10.3.11
    - 10.3.4
    - 10.3.7
    - 10.3.9
    - 10.4.0
  - dependency-name: NSwag.AspNetCore
    versions:
    - 13.10.2
    - 13.10.5
    - 13.10.7
    - 13.10.8
  - dependency-name: NSwag.Generation
    versions:
    - 13.10.2
    - 13.10.5
    - 13.10.7
    - 13.10.8
  - dependency-name: NSwag.Core
    versions:
    - 13.10.2
    - 13.10.5
    - 13.10.7
    - 13.10.8
  - dependency-name: NSwag.Annotations
    versions:
    - 13.10.2
    - 13.10.5
    - 13.10.7
    - 13.10.8
  - dependency-name: LinqKit.Microsoft.EntityFrameworkCore
    versions:
    - 5.0.23
  - dependency-name: Bogus
    versions:
    - 33.0.1
  - dependency-name: Microsoft.Azure.Management.ServiceBus.Fluent
    versions:
    - 1.37.0
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: System.Data.SQLite.Core
    versions:
    - 1.0.113.7
  - dependency-name: System.Data.SQLite
    versions:
    - 1.0.113.7
  - dependency-name: MessagePack
    versions:
    - 2.2.85
  - dependency-name: AutoMapper.Extensions.ExpressionMapping
    versions:
    - 4.1.0
  - dependency-name: AutoMapper
    versions:
    - 10.1.1
  - dependency-name: MediatR
    versions:
    - 9.0.0
  - dependency-name: MediatR.Extensions.Microsoft.DependencyInjection
    versions:
    - 9.0.0
  - dependency-name: Microsoft.IdentityModel.Clients.ActiveDirectory
    versions:
    - 5.2.8
